# Generated by Django 5.2.2 on 2025-06-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_cta_link_1',
            field=models.ForeignKey(blank=True, help_text='Link for the first call to action button.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_cta_link_2',
            field=models.ForeignKey(blank=True, help_text='Link for the first call to action button.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_header',
            field=models.CharField(blank=True, help_text='Text to display on the banner.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_subheader',
            field=models.TextField(blank=True, help_text='Subtext to display on the banner.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='profile_image',
            field=models.ForeignKey(blank=True, help_text='Upload your profile image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
