# Generated by Django 5.2.3 on 2025-06-25 10:15

from django.db import migrations
import json

def convert_to_streamfield(apps, schema_editor):
    HomePage = apps.get_model('home', 'HomePage')
    
    for page in HomePage.objects.all():
        if page.body and not page.body.startswith('['):  # If it's not already a StreamField JSON
            # Convert RichText to StreamField format
            new_body = json.dumps([
                {
                    "type": "heading",
                    "value": {
                        "heading_text": "About Me",
                        "size": "h2"
                    },
                    "id": "1"
                },
                {
                    "type": "paragraph",  # This assumes you have a paragraph block
                    "value": page.body,
                    "id": "2"
                }
            ])
            
            # Direct database update to avoid model validation
            HomePage.objects.filter(id=page.id).update(body=new_body)

def reverse_convert_to_streamfield(apps, schema_editor):
    HomePage = apps.get_model('home', 'HomePage')
    
    for page in HomePage.objects.all():
        if page.body and isinstance(page.body, str):
            # Convert StreamField JSON back to RichText
            body_data = json.loads(page.body)
            rich_text_content = ""
            for block in body_data:
                if block['type'] == 'paragraph':
                    rich_text_content += block['value'] + "\n\n"
                elif block['type'] == 'heading':
                    rich_text_content += f"<h2>{block['value']['heading_text']}</h2>\n"
            
            # Direct database update to avoid model validation
            HomePage.objects.filter(id=page.id).update(body=rich_text_content)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customize_the_home_page'),  # Change this to your previous migration
    ]

    operations = [
        migrations.RunPython(convert_to_streamfield, reverse_convert_to_streamfield),
    ]

